name: GenAI-project
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - jupyter
  - ipykernel
  - matplotlib
  - scipy
  - scikit-learn
  - tqdm
  - opencv
  - pyyaml
  - pip
  - pip:
    - transformers
    - diffusers
    - accelerate
    - safetensors
    - pillow
    - pillow-avif-plugin
    - huggingface_hub
    - ultralytics
    - torch-directml