name: GenAI-project
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - jupyter
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - diffusers
  - transformers
  - accelerate
  - pillow
  - scipy
  - pillow-avif-plugin
  - opencv